## Collecting Movie Links

In [27]:
import pickle

In [37]:
with open("all_movie", "rb") as f:
    movie_dict = pickle.load(f)

In [1]:
from selenium import webdriver

In [41]:
driver = webdriver.Chrome('/Applications/chromedriver')

In [3]:
driver.get("https://www.imdb.com/")

In [33]:
imdb_movies = {}
for movie in movie_dict:
    try:
        name = movie_dict[movie].split()
        driver.get("https://www.imdb.com/find?q="+"+".join(name))
        imdb_movies[movie] = {}
        imdb_movies[movie]["Title_en"] = movie_dict[movie]
        imdb_movies[movie]["Title_zh"] = driver.find_element_by_xpath('//*[@id="main"]/div/div[2]/table/tbody/tr[1]/td[2]/a').get_attribute("text")
        imdb_movies[movie]["URL"] = driver.find_element_by_xpath('//*[@id="main"]/div/div[2]/table/tbody/tr[1]/td[2]/a').get_attribute("href")
    except:
        print(movie_dict[movie])

In [1]:
import pandas as pd

In [42]:
df = pd.DataFrame.from_dict(imdb_movies, orient='index')
df

,Title_en,Title_zh,URL
m0,10 things i hate about you,對面惡女看過來,https://www.imdb.com/title/tt0147800/?ref_=fn_...
m1,1492: conquest of paradise,1492: 征服天堂,https://www.imdb.com/title/tt0103594/?ref_=fn_...
m2,15 minutes,千鈞一刻,https://www.imdb.com/title/tt0179626/?ref_=fn_...
m3,2001: a space odyssey,2001：太空漫遊,https://www.imdb.com/title/tt0062622/?ref_=fn_...
m4,48 hrs.,48小時,https://www.imdb.com/title/tt0083511/?ref_=fn_...
...,...,...,...
m612,watchmen,守護者,https://www.imdb.com/title/tt0409459/?ref_=fn_...
m613,xxx,限制級戰警,https://www.imdb.com/title/tt0295701/?ref_=fn_...
m614,x-men,X戰警,https://www.imdb.com/title/tt0120903/?ref_=fn_...
m615,young frankenstein,新科學怪人,https://www.imdb.com/title/tt0072431/?ref_=fn_...
m616,zulu dawn,Zulu Dawn,https://www.imdb.com/title/tt0080180/?ref_=fn_...

In [43]:
df = df.join(pd.DataFrame.from_dict(movie_dict, orient='index'))
df

,Title_en,Title_zh,URL,title,year
m0,10 things i hate about you,對面惡女看過來,https://www.imdb.com/title/tt0147800/?ref_=fn_...,10 things i hate about you,1999
m1,1492: conquest of paradise,1492: 征服天堂,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1492: conquest of paradise,1992
m2,15 minutes,千鈞一刻,https://www.imdb.com/title/tt0179626/?ref_=fn_...,15 minutes,2001
m3,2001: a space odyssey,2001：太空漫遊,https://www.imdb.com/title/tt0062622/?ref_=fn_...,2001: a space odyssey,1968
m4,48 hrs.,48小時,https://www.imdb.com/title/tt0083511/?ref_=fn_...,48 hrs.,1982
...,...,...,...,...,...
m612,watchmen,守護者,https://www.imdb.com/title/tt0409459/?ref_=fn_...,watchmen,2009
m613,xxx,限制級戰警,https://www.imdb.com/title/tt0295701/?ref_=fn_...,xxx,2002
m614,x-men,X戰警,https://www.imdb.com/title/tt0120903/?ref_=fn_...,x-men,2000
m615,young frankenstein,新科學怪人,https://www.imdb.com/title/tt0072431/?ref_=fn_...,young frankenstein,1974
m616,zulu dawn,Zulu Dawn,https://www.imdb.com/title/tt0080180/?ref_=fn_...,zulu dawn,1979

In [44]:
df = df.drop('title', axis=1)
df

,Title_en,Title_zh,URL,year
m0,10 things i hate about you,對面惡女看過來,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999
m1,1492: conquest of paradise,1492: 征服天堂,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992
m2,15 minutes,千鈞一刻,https://www.imdb.com/title/tt0179626/?ref_=fn_...,2001
m3,2001: a space odyssey,2001：太空漫遊,https://www.imdb.com/title/tt0062622/?ref_=fn_...,1968
m4,48 hrs.,48小時,https://www.imdb.com/title/tt0083511/?ref_=fn_...,1982
...,...,...,...,...
m612,watchmen,守護者,https://www.imdb.com/title/tt0409459/?ref_=fn_...,2009
m613,xxx,限制級戰警,https://www.imdb.com/title/tt0295701/?ref_=fn_...,2002
m614,x-men,X戰警,https://www.imdb.com/title/tt0120903/?ref_=fn_...,2000
m615,young frankenstein,新科學怪人,https://www.imdb.com/title/tt0072431/?ref_=fn_...,1974
m616,zulu dawn,Zulu Dawn,https://www.imdb.com/title/tt0080180/?ref_=fn_...,1979

In [73]:
df = df.reset_index()

In [74]:
df

,index,Title_en,Title_zh,URL,year
0,m0,10 things i hate about you,對面惡女看過來,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999
1,m1,1492: conquest of paradise,1492: 征服天堂,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992
2,m2,15 minutes,千鈞一刻,https://www.imdb.com/title/tt0179626/?ref_=fn_...,2001
3,m3,2001: a space odyssey,2001：太空漫遊,https://www.imdb.com/title/tt0062622/?ref_=fn_...,1968
4,m4,48 hrs.,48小時,https://www.imdb.com/title/tt0083511/?ref_=fn_...,1982
...,...,...,...,...,...
612,m612,watchmen,守護者,https://www.imdb.com/title/tt0409459/?ref_=fn_...,2009
613,m613,xxx,限制級戰警,https://www.imdb.com/title/tt0295701/?ref_=fn_...,2002
614,m614,x-men,X戰警,https://www.imdb.com/title/tt0120903/?ref_=fn_...,2000
615,m615,young frankenstein,新科學怪人,https://www.imdb.com/title/tt0072431/?ref_=fn_...,1974
616,m616,zulu dawn,Zulu Dawn,https://www.imdb.com/title/tt0080180/?ref_=fn_...,1979

In [77]:
for i in range(len(df)):
    driver.get(df.iloc[i].URL)
    a = driver.find_element_by_xpath('//*[@id="__next"]/main/div/section[1]/section/div[3]/section/section/div[1]/div[1]/div/ul/li[1]')
    if a.text!= df.iloc[i].year:
        print(df.iloc[i].Title_en)

the avengers
bad lieutenant
black rain
blast from the past
dark angel
fantastic four
frankenstein
godzilla
ghost ship
ghostbusters
grand hotel
hardcore
hellboy
invaders from mars
jacob's ladder
lon

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="__next"]/main/div/section[1]/section/div[3]/section/section/div[1]/div[1]/div/ul/li[1]"}
  (Session info: chrome=100.0.4896.127)

In [86]:
df[df.Title_en == 'roughshod']

,index,Title_en,Title_zh,URL,year
171,m171,roughshod,Gunsmoke,https://www.imdb.com/title/tt0045847/?ref_=fn_...,1949

In [112]:
wrong_df = pd.read_csv('wrongURL.csv')
wrong_df

,index,Title_en,URL,year,Problem
0,m23,the avengers,https://www.imdb.com/title/tt0118661/?ref_=fn_...,1998,NaN
1,m26,bad lieutenant,https://www.imdb.com/title/tt0103759/?ref_=fn_...,1992,NaN
2,m33,black rain,https://www.imdb.com/title/tt0096933/,1989,NaN
3,m35,blast from the past,https://www.imdb.com/title/tt0124298/?ref_=fn_...,1998,NaN
4,m48,dark angel,https://www.imdb.com/title/tt0099817/?ref_=fn_...,1990,NaN
...,...,...,...,...,...
88,m591,unforgiven,https://www.imdb.com/title/tt0105695/?ref_=nv_...,1992,NaN
89,m593,verdict,https://www.imdb.com/title/tt0072359/?ref_=fn_...,1974,NaN
90,m603,the witching hour,https://www.imdb.com/title/tt0181904/?ref_=fn_...,1996,NaN
91,m604,white angel,https://www.imdb.com/title/tt0108558/?ref_=fn_...,1994,NaN
92,m605,who's your daddy?,https://www.imdb.com/title/tt0287138/,2002,1.0

In [108]:
df['Problem'] = df.Title_en.apply(lambda x: 1 if x in list(wrong_df.Title_en) else 0)

,index,Title_en,Title_zh,URL,year,Problem
0,m0,10 things i hate about you,對面惡女看過來,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0
1,m1,1492: conquest of paradise,1492: 征服天堂,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0
2,m2,15 minutes,千鈞一刻,https://www.imdb.com/title/tt0179626/?ref_=fn_...,2001,0
3,m3,2001: a space odyssey,2001：太空漫遊,https://www.imdb.com/title/tt0062622/?ref_=fn_...,1968,0
4,m4,48 hrs.,48小時,https://www.imdb.com/title/tt0083511/?ref_=fn_...,1982,0
...,...,...,...,...,...,...
612,m612,watchmen,守護者,https://www.imdb.com/title/tt0409459/?ref_=fn_...,2009,0
613,m613,xxx,限制級戰警,https://www.imdb.com/title/tt0295701/?ref_=fn_...,2002,0
614,m614,x-men,X戰警,https://www.imdb.com/title/tt0120903/?ref_=fn_...,2000,0
615,m615,young frankenstein,新科學怪人,https://www.imdb.com/title/tt0072431/?ref_=fn_...,1974,0
616,m616,zulu dawn,Zulu Dawn,https://www.imdb.com/title/tt0080180/?ref_=fn_...,1979,0

In [110]:
df[df['Problem']==1].to_csv('wrongURL.csv', index=False)

In [113]:
wrong_df

,index,Title_en,URL,year,Problem
0,m23,the avengers,https://www.imdb.com/title/tt0118661/?ref_=fn_...,1998,NaN
1,m26,bad lieutenant,https://www.imdb.com/title/tt0103759/?ref_=fn_...,1992,NaN
2,m33,black rain,https://www.imdb.com/title/tt0096933/,1989,NaN
3,m35,blast from the past,https://www.imdb.com/title/tt0124298/?ref_=fn_...,1998,NaN
4,m48,dark angel,https://www.imdb.com/title/tt0099817/?ref_=fn_...,1990,NaN
...,...,...,...,...,...
88,m591,unforgiven,https://www.imdb.com/title/tt0105695/?ref_=nv_...,1992,NaN
89,m593,verdict,https://www.imdb.com/title/tt0072359/?ref_=fn_...,1974,NaN
90,m603,the witching hour,https://www.imdb.com/title/tt0181904/?ref_=fn_...,1996,NaN
91,m604,white angel,https://www.imdb.com/title/tt0108558/?ref_=fn_...,1994,NaN
92,m605,who's your daddy?,https://www.imdb.com/title/tt0287138/,2002,1.0

In [114]:
df = df.drop(['Title_zh'], axis = 1)
df

,index,Title_en,URL,year,Problem
0,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0
1,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0
2,m2,15 minutes,https://www.imdb.com/title/tt0179626/?ref_=fn_...,2001,0
3,m3,2001: a space odyssey,https://www.imdb.com/title/tt0062622/?ref_=fn_...,1968,0
4,m4,48 hrs.,https://www.imdb.com/title/tt0083511/?ref_=fn_...,1982,0
...,...,...,...,...,...
612,m612,watchmen,https://www.imdb.com/title/tt0409459/?ref_=fn_...,2009,0
613,m613,xxx,https://www.imdb.com/title/tt0295701/?ref_=fn_...,2002,0
614,m614,x-men,https://www.imdb.com/title/tt0120903/?ref_=fn_...,2000,0
615,m615,young frankenstein,https://www.imdb.com/title/tt0072431/?ref_=fn_...,1974,0
616,m616,zulu dawn,https://www.imdb.com/title/tt0080180/?ref_=fn_...,1979,0

In [115]:
df = df[df['Problem']==0]

In [116]:
df

,index,Title_en,URL,year,Problem
0,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0
1,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0
2,m2,15 minutes,https://www.imdb.com/title/tt0179626/?ref_=fn_...,2001,0
3,m3,2001: a space odyssey,https://www.imdb.com/title/tt0062622/?ref_=fn_...,1968,0
4,m4,48 hrs.,https://www.imdb.com/title/tt0083511/?ref_=fn_...,1982,0
...,...,...,...,...,...
612,m612,watchmen,https://www.imdb.com/title/tt0409459/?ref_=fn_...,2009,0
613,m613,xxx,https://www.imdb.com/title/tt0295701/?ref_=fn_...,2002,0
614,m614,x-men,https://www.imdb.com/title/tt0120903/?ref_=fn_...,2000,0
615,m615,young frankenstein,https://www.imdb.com/title/tt0072431/?ref_=fn_...,1974,0
616,m616,zulu dawn,https://www.imdb.com/title/tt0080180/?ref_=fn_...,1979,0

In [118]:
df = pd.concat([df, wrong_df]).fillna(0)

In [121]:
df

,index,Title_en,URL,year,Problem
0,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0.0
1,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0.0
10,m10,affliction,https://www.imdb.com/title/tt0118564/?ref_=fn_...,1997,0.0
100,m100,innerspace,https://www.imdb.com/title/tt0093260/?ref_=fn_...,1987,0.0
101,m101,the insider,https://www.imdb.com/title/tt0140352/?ref_=fn_...,1999,0.0
...,...,...,...,...,...
95,m95,i am legend,https://www.imdb.com/title/tt0480249/?ref_=fn_...,2007,0.0
13,m96,invaders from mars,https://www.imdb.com/title/tt0045917/?ref_=nv_...,1953,0.0
97,m97,independence day,https://www.imdb.com/title/tt0116629/?ref_=fn_...,1996,0.0
98,m98,indiana jones and the last crusade,https://www.imdb.com/title/tt0097576/?ref_=fn_...,1989,0.0
99,m99,indiana jones and the temple of doom,https://www.imdb.com/title/tt0087469/?ref_=fn_...,1984,0.0

In [122]:
df.to_csv('movies_on_imdb.csv', index = False)

## Crawling things from IMDB

In [125]:
vid = "https://imdb-video.media-imdb.com/vi911933977/1434659607842-pgv4ql-1564475086450.mp4?Expires=1650598217&Signature=Z1KnKgoIv04se61ypLv1~Yv8ux~0KbmmysY2n2~Nl8YcOQ5-r7wNnWvYepZI3PWatUQU2ZDxFJy-OlcoyFRWLaE8iHZe8Dq8GUf~h6Uqljy4-x96RKVs5RL1BDHYucgqFp0LoS4GxCTTpDS8IcM37mNOqm21tkPGXKzYqCc6Y0w3LH-h-vNS7WURg8wB0qC-z2H53WPsYB0krKHA9d6YrXs4hV8aaFLN-qzuNEYLhLZ~su3awN3j7b4aenX9QOX9UpoXNaO~INbiykeff-t2918j1gznevUlov8UidKB20OOGS9P0ytU7Ol83r3v64l1xzv5yAr3~HEoYa5oez6OIQ__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA"

In [3]:
import urllib.request
# urllib.request.urlretrieve(vid, "vid.mp4")

In [127]:
driver = webdriver.Chrome('/Applications/chromedriver')
driver.get(df.iloc[0].URL)

In [131]:
vid_url = driver.find_element_by_xpath('//*[@id="__next"]/main/div/section[1]/section/div[3]/section/section/div[3]/div[1]/div/div[2]/div[2]/a').get_attribute('href')
driver.get(vid_url)

In [134]:
vid_url = driver.find_element_by_xpath('//*[@id="imdbnext-vp-jw"]/div[2]/div[4]/video').get_attribute('src')
vid_url

'https://imdb-video.media-imdb.com/vi911933977/1434659607842-pgv4ql-1564475086450.mp4?Expires=1650599725&Signature=P4a1u5R2r5kXZ6-bfaIaBR8WFVeiwWpM7AIVu23ZYlCaEcztVOPGKSLU3Y3NamiYlEgWPGjNEe2ABacHuxWGWEELbh-54osOPbGOSUaFtN154FaM8gpj6gn-nL8vktVZpmi5ihvJSVHIs4u3Q-k7SmCys0GA1JDbnJwfJqM~kYElm3hvAL45QRrG8m8fEdaRgiMfdclDWhknt~Wj4zJ7X99msdcfUor7m~p3wUbML2TMppuCX0rn~enq~aKFamrC6ZwST1zdlbFYWhAJ95yoEi62KPfKuOl6kFMFKK4on8egmnCcr~2E6tesV7eTHv3KACV0I7IB9BX1m7PaVtpVLw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA'

In [ ]:
urllib.request.urlretrieve(vid, "vid.mp4")

In [150]:
driver.find_element_by_xpath('//*[@id="imdbnext-vp-jw"]/div[2]/div[4]/video').get_attribute('src')

'https://imdb-video.media-imdb.com/vi727695641/1434659607842-pgv4ql-1613057245744.mp4?Expires=1650600768&Signature=C4uLjD~8clNDg-UY309utvaXBtvG69T7FQj0ad9UJo5Eo1zv8MUSY~n0OsBIWwQFvqytst4gdLgnj~u9MSpGI2gAZo~feKYnJz5oKyFBirYve9~hyOcP4EQqep6uVIHIxhnmy8YYb9A9dRc1nuu9LoUr55FyXPX2aVo4vROimziZKsDmTLUKgwW~1kby9XlvOvFDkoq~OouO0jmCx1p~VaelzRLjEyzKdYhmtvkqmVYFr48eHc03r4WY2fBpraaxsIAh~TpAz42YUgIbZOKMElGKDWcTMr-GrVob~SHfmdpg1mT66rsKiithkJzQHv48So8oVuYG9fkKZDbSmv7tmw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA'

In [1]:
import time
import pandas as pd

In [2]:
df = pd.read_csv('IMDB_infos.csv')
df.head()

,IMDBid,index,Title_en,URL,year,Problem,poster_url,trailer_url,IMDB,MetaCritic,theMovieDb,RottenTomatoes,FilmAffinity,IMDB_male,IMDB_female,budget,openWeek,WorldGross,USCAGross
0,tt0147800,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0.0,NaN,https://www.imdb.com/video/vi911933977,7.3,70.0,7.6,70.0,5.8,7.0,7.8,30000000.0,8330681.0,53478579.0,38178166.0
1,tt0103594,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0.0,https://imdb-api.com/posters/original/xVEynmeq...,https://www.imdb.com/video/vi1549188633,6.4,47.0,6.2,32.0,5.8,6.4,6.4,47000000.0,3002680.0,7191399.0,7191399.0
2,tt0118564,m10,affliction,https://www.imdb.com/title/tt0118564/?ref_=fn_...,1997,0.0,https://imdb-api.com/posters/original/hNu8ePwo...,https://www.imdb.com/video/vi727695641,6.9,79.0,6.4,88.0,7.1,6.9,6.7,6000000.0,63979.0,6330054.0,6330054.0
3,tt0093260,m100,innerspace,https://www.imdb.com/title/tt0093260/?ref_=fn_...,1987,0.0,https://imdb-api.com/posters/original/A4azclZQ...,https://www.imdb.com/video/vi4136698137,6.8,66.0,6.8,82.0,6.3,6.8,6.9,27000000.0,4739913.0,25893810.0,25893810.0
4,tt0140352,m101,the insider,https://www.imdb.com/title/tt0140352/?ref_=fn_...,1999,0.0,https://imdb-api.com/posters/original/w695X0Fv...,https://www.imdb.com/video/vi1173618969,7.8,84.0,7.5,96.0,7.2,7.9,7.7,90000000.0,6712361.0,60289912.0,29089912.0

In [35]:
def get_video(index, url):
#     driver.get(url)
    try:
#         vid_url = driver.find_element_by_xpath('//*[@id="__next"]/main/div/section[1]/section/div[3]/section/section/div[3]/div[1]/div/div[2]/div[2]/a').get_attribute('href')
        driver.get(url)
        try:
            time.sleep(20)
            vid_url = driver.find_element_by_xpath('//*[@id="imdbnext-vp-jw"]/div[2]/div[4]/video').get_attribute('src')
            urllib.request.urlretrieve(vid_url,  "trailers_vid/"+index+".mp4")
        except:
            try:
                time.sleep(10)
                vid_url = driver.find_element_by_xpath('//*[@id="imdbnext-vp-jw"]/div[2]/div[4]/video').get_attribute('src')
                urllib.request.urlretrieve(vid_url, "trailers_vid/"+index+".mp4")
                return False
            except:
                print(index)
                return True
    except:
        print(index, 'first')
        return True

In [36]:
redos = []
for i in range(41, 100):
    if get_video(df.iloc[i]['index'], df.iloc[i].trailer_url):
        redos.append(i)

m136
m137 first
m138 first
m139
m14
m140
m141
m142
m143
m144
m145
m146 first
m147
m148
m149
m15
m150
m151
m152
m153
m154
m156
m157
m158
m159
m160 first
m161 first
m162
m163
m164
m165
m166
m167
m168
m169 first
m17
m170
m171 first
m172
m173
m174
m175
m176
m177
m178
m179
m18 first
m180
m181
m183
m184 first
m185
m186
m187
m188

In [44]:
redo_dupl = redos[:]
redos = []

for i in redo_dupl:
    if get_video(df.iloc[i]['index'], df.iloc[i].trailer_url):
        redos.append(i)

m137 first
m138 first
m14
m140
m141
m142
m143
m144
m145
m146 first
m147
m148
m149
m15
m153
m156
m160 first
m161 first
m164
m165
m166
m167
m168
m169 first
m17
m170
m171 first
m172
m174
m176
m177
m179
m18 first
m183
m184 first
m185
m186
m188

In [164]:
get_video(df.iloc[9]['index'], df.iloc[9]['URL'])

#### IMDB IDs

In [242]:
df = pd.read_csv('movies_on_imdb.csv')
df

,index,Title_en,URL,year,Problem
0,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0.0
1,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0.0
2,m10,affliction,https://www.imdb.com/title/tt0118564/?ref_=fn_...,1997,0.0
3,m100,innerspace,https://www.imdb.com/title/tt0093260/?ref_=fn_...,1987,0.0
4,m101,the insider,https://www.imdb.com/title/tt0140352/?ref_=fn_...,1999,0.0
...,...,...,...,...,...
612,m95,i am legend,https://www.imdb.com/title/tt0480249/?ref_=fn_...,2007,0.0
613,m96,invaders from mars,https://www.imdb.com/title/tt0045917/?ref_=nv_...,1953,0.0
614,m97,independence day,https://www.imdb.com/title/tt0116629/?ref_=fn_...,1996,0.0
615,m98,indiana jones and the last crusade,https://www.imdb.com/title/tt0097576/?ref_=fn_...,1989,0.0
616,m99,indiana jones and the temple of doom,https://www.imdb.com/title/tt0087469/?ref_=fn_...,1984,0.0

In [243]:
df['IMDBid'] = df.URL.apply(lambda x: x.split('/')[4])
df.loc[72,'IMDBid'] = 'tt0063518'

In [244]:
df.to_csv('movies_on_imdb.csv', index=False)

### What we need:
`api_key`: k_vrg9qwye
* IMDB ID
* Posters(ImgURL):https://imdb-api.com/en/API/Posters/{api_key}/{id}
* Trailers(TrailerURL): https://imdb-api.com/en/API/Trailer/{api_key}/{id}
* Ratings(`imDb`,`metacritic`, `theMovieDb`, `rottenTomatoes`, `filmAffinity`):https://imdb-api.com/en/API/Ratings/{api_key}/{id}
* UserRatings(`total`, `Demographic(ages, genders, user region)`):https://imdb-api.com/en/API/UserRatings/{api_key}/{id}
* Reviews: https://imdb-api.com/en/API/Reviews/{api_key}/{id}
* Wikipedia: https://imdb-api.com/en/API/Wikipedia/{api_key}/{id}
* Casts(All): https://imdb-api.com/en/API/FullCast/{api_key}/{id}

For now, 100 api calls per day. Do we need to upgrade for a larger amount calls?


* StoryLine/Plot/Synopsis: https://www.imdb.com/title/tt0090022/plotsummary
#### Box Office (need to write codes lol)
* Budget
* Gross US & Canada
* Opening weekend US & Canada
* Gross worldwide

In [194]:
imdb_api_infos = {}

In [175]:
import requests
import json

In [176]:
api_key = 'k_vrg9qwye'

#### Posters

In [205]:
for movie in df['IMDBid']:
#     try:
    url = f"https://imdb-api.com/en/API/Posters/{api_key}/{movie}"
    payload = {}
    headers= {}
    response = requests.request("GET", url, headers=headers, data = payload)
    imdb_api_infos[movie] = {}
    posters = json.loads(response.text.encode('utf8'))['posters']
    if len(posters) > 0:
        imdb_api_infos[movie]['poster_url'] = posters[0]['link']
    else:
        imdb_api_infos[movie]['poster_url'] = ''
#     except:
#         print(movie)

In [206]:
no_poster = 0
for movie in imdb_api_infos:
    if imdb_api_infos[movie]['poster_url'] == '':
        no_poster += 1
print(no_poster)

92

#### Trailers

In [212]:
for movie in df['IMDBid']:
#     try:
    url = f"https://imdb-api.com/en/API/Trailer/{api_key}/{movie}"
    payload = {}
    headers= {}
    response = requests.request("GET", url, headers=headers, data = payload)
    try:
        trailer = json.loads(response.text.encode('utf8'))['link']
        imdb_api_infos[movie]['trailer_url'] = trailer
    except:
        imdb_api_infos[movie]['trailer_url'] = ''
#     except:
#         print(movie)

In [213]:
no_trailer = 0
for movie in imdb_api_infos:
    if imdb_api_infos[movie]['trailer_url'] == '':
        no_trailer += 1
print(no_trailer)

1

#### Rating

In [219]:
for movie in df['IMDBid']:
#     try:
    url = f"https://imdb-api.com/en/API/Ratings/{api_key}/{movie}"
    payload = {}
    headers= {}
    response = requests.request("GET", url, headers=headers, data = payload)
    try:
        score = json.loads(response.text.encode('utf8'))['imDb']
        imdb_api_infos[movie]['IMDB'] = score
    except:
        imdb_api_infos[movie]['IMDB'] = ''
    try:
        score = json.loads(response.text.encode('utf8'))['metacritic']
        imdb_api_infos[movie]['MetaCritic'] = score
    except:
        imdb_api_infos[movie]['MetaCritic'] = ''
    try:
        score = json.loads(response.text.encode('utf8'))['theMovieDb']
        imdb_api_infos[movie]['theMovieDb'] = score
    except:
        imdb_api_infos[movie]['theMovieDb'] = ''
    try:
        score = json.loads(response.text.encode('utf8'))['rottenTomatoes']
        imdb_api_infos[movie]['RottenTomatoes'] = score
    except:
        imdb_api_infos[movie]['RottenTomatoes'] = ''
    try:
        score = json.loads(response.text.encode('utf8'))['filmAffinity']
        imdb_api_infos[movie]['FilmAffinity'] = score
    except:
        imdb_api_infos[movie]['FilmAffinity'] = ''
#     break

In [220]:
no_IMDB = 0
no_MetaCritic = 0
no_theMovieDb = 0
no_RottenTomatoes = 0
no_FilmAffinity = 0

for movie in imdb_api_infos:
    if imdb_api_infos[movie]['IMDB'] == '':
        no_IMDB += 1
    if imdb_api_infos[movie]['MetaCritic'] == '':
        no_MetaCritic += 1
    if imdb_api_infos[movie]['theMovieDb'] == '':
        no_theMovieDb += 1
    if imdb_api_infos[movie]['RottenTomatoes'] == '':
        no_RottenTomatoes += 1
    if imdb_api_infos[movie]['FilmAffinity'] == '':
        no_FilmAffinity += 1
print(no_IMDB,no_MetaCritic,no_theMovieDb,no_RottenTomatoes,no_FilmAffinity)

0 86 9 75 19

#### UserRatings

In [231]:
for movie in df['IMDBid']:
#     try:
    url = f"https://imdb-api.com/en/API/UserRatings/{api_key}/{movie}"
    payload = {}
    headers= {}
    response = requests.request("GET", url, headers=headers, data = payload)
    try:
        score = json.loads(response.text.encode('utf8'))['demographicMales']['allAges']['rating']
        imdb_api_infos[movie]['IMDB_male'] = score
    except:
        imdb_api_infos[movie]['IMDB_male'] = ''
    try:
        score = json.loads(response.text.encode('utf8'))['demographicFemales']['allAges']['rating']
        imdb_api_infos[movie]['IMDB_female'] = score
    except:
        imdb_api_infos[movie]['IMDB_female'] = ''

In [232]:
no_male = 0
no_female = 0

for movie in imdb_api_infos:
    if imdb_api_infos[movie]['IMDB_male'] == '':
        no_male += 1
    if imdb_api_infos[movie]['IMDB_female'] == '':
        no_female += 1
print(no_male, no_female)

5 5

In [254]:
df = df.reset_index().set_index('IMDBid')

In [252]:
api_result = pd.DataFrame.from_dict(imdb_api_infos, orient='index').reset_index().set_index('index')
api_result

,poster_url,trailer_url,IMDB,MetaCritic,theMovieDb,RottenTomatoes,FilmAffinity,IMDB_male,IMDB_female
index,,,,,,,,,
tt0147800,,https://www.imdb.com/video/vi911933977,7.3,70,7.6,70,5.8,7.0,7.8
tt0103594,https://imdb-api.com/posters/original/xVEynmeq...,https://www.imdb.com/video/vi1549188633,6.4,47,6.2,32,5.8,6.4,6.4
tt0118564,https://imdb-api.com/posters/original/hNu8ePwo...,https://www.imdb.com/video/vi727695641,6.9,79,6.4,88,7.1,6.9,6.7
tt0093260,https://imdb-api.com/posters/original/A4azclZQ...,https://www.imdb.com/video/vi4136698137,6.8,66,6.8,82,6.3,6.8,6.9
tt0140352,https://imdb-api.com/posters/original/w695X0Fv...,https://www.imdb.com/video/vi1173618969,7.8,84,7.5,96,7.2,7.9,7.7
...,...,...,...,...,...,...,...,...,...
tt0480249,https://imdb-api.com/posters/original/iPDkaSdK...,https://www.imdb.com/video/vi3820028185,7.2,65,7.2,68,6.5,7.2,7.2
tt0045917,https://imdb-api.com/posters/original/pVR2c0bi...,https://www.imdb.com/video/vi3986670361,6.3,,6.0,82,5.7,6.2,6.4
tt0116629,https://imdb-api.com/posters/original/p0BPQGSP...,https://www.imdb.com/video/vi2181957401,7,59,6.8,68,5.3,7.0,7.1
tt0097576,https://imdb-api.com/posters/original/sizg1AU8...,https://www.imdb.com/video/vi2007669529,8.2,65,7.8,88,7.8,8.3,8.1
tt0087469,https://imdb-api.com/posters/original/wdv7Edut...,https://www.imdb.com/video/vi2444476697,7.5,57,7.3,84,7.4,7.5,7.5

In [257]:
df = df.join(api_result)

In [258]:
df.to_csv('IMDB_with_api.csv')

#### Reviews

In [1]:
import pandas as pd
df = pd.read_csv('IMDB_infos.csv')
df.head()

,IMDBid,index,Title_en,URL,year,Problem,poster_url,trailer_url,IMDB,MetaCritic,theMovieDb,RottenTomatoes,FilmAffinity,IMDB_male,IMDB_female,budget,openWeek,WorldGross,USCAGross
0,tt0147800,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0.0,NaN,https://www.imdb.com/video/vi911933977,7.3,70.0,7.6,70.0,5.8,7.0,7.8,30000000.0,8330681.0,53478579.0,38178166.0
1,tt0103594,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0.0,https://imdb-api.com/posters/original/xVEynmeq...,https://www.imdb.com/video/vi1549188633,6.4,47.0,6.2,32.0,5.8,6.4,6.4,47000000.0,3002680.0,7191399.0,7191399.0
2,tt0118564,m10,affliction,https://www.imdb.com/title/tt0118564/?ref_=fn_...,1997,0.0,https://imdb-api.com/posters/original/hNu8ePwo...,https://www.imdb.com/video/vi727695641,6.9,79.0,6.4,88.0,7.1,6.9,6.7,6000000.0,63979.0,6330054.0,6330054.0
3,tt0093260,m100,innerspace,https://www.imdb.com/title/tt0093260/?ref_=fn_...,1987,0.0,https://imdb-api.com/posters/original/A4azclZQ...,https://www.imdb.com/video/vi4136698137,6.8,66.0,6.8,82.0,6.3,6.8,6.9,27000000.0,4739913.0,25893810.0,25893810.0
4,tt0140352,m101,the insider,https://www.imdb.com/title/tt0140352/?ref_=fn_...,1999,0.0,https://imdb-api.com/posters/original/w695X0Fv...,https://www.imdb.com/video/vi1173618969,7.8,84.0,7.5,96.0,7.2,7.9,7.7,90000000.0,6712361.0,60289912.0,29089912.0

In [2]:
import requests
from bs4 import BeautifulSoup
from dateutil.parser import parse

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

In [6]:
cnt = 0
for movie in df['IMDBid']:
    try:
        url = "https://www.imdb.com/title/"+movie+"/reviews/_ajax?ref_=undefined&paginationKey={}"
        key = "g4wp7bbfqqydoyyh7ovxrmbvrptm6cjhzfmxvlnomwklyczuf43o6ss7pe4vrprndr4k5xbfpgn3rldoq3jzj74iui53agq"
        data = {"title": [], "user":[], "rating":[], "date":[], 'spoil':[], "review": []}

        while True:
            response = requests.get(url.format(key))
            soup = BeautifulSoup(response.content, "html.parser")
            # Find the pagination key
            pagination_key = soup.find("div", class_="load-more-data")
            if not pagination_key:
                break
            # Update the `key` variable in-order to scrape more reviews
            key = pagination_key["data-key"]
            for title, review, date, user, content in zip(
                soup.find_all(class_="title"), 
                soup.find_all(class_="text show-more__control"), 
                soup.find_all(class_="review-date"),
                soup.find_all(class_="display-name-link"), 
                soup.findAll(class_='lister-item-content')
            ):
                data["title"].append(title.get_text(strip=True))
                data["review"].append(review.get_text())

                data["date"].append(parse(date.get_text()).strftime("%Y-%m-%d"))
                data["user"].append(user.find('a')['href'].split('/')[-2])
                if content.find(class_='spoiler-warning')!=None:
                    data["spoil"].append(1)
                else:
                    data["spoil"].append(0)
                if content.find(class_='rating-other-user-rating')!=None:
                    data["rating"].append(content.find(class_='rating-other-user-rating').get_text(strip=True).split('/')[0])
                else:
                    data["rating"].append(None)
        pd.DataFrame(data).to_csv('reviews_rat/'+movie+'.csv', index=False)
    except:
        print(movie)
    print(cnt, end=' ')
    cnt += 1

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616

In [3]:
movie = df['IMDBid'][0]
movie

'tt0147800'

In [5]:
url = "https://www.imdb.com/title/"+movie+"/reviews/_ajax?ref_=undefined&paginationKey={}"
key = "g4wp7bbfqqydoyyh7ovxrmbvrptm6cjhzfmxvlnomwklyczuf43o6ss7pe4vrprndr4k5xbfpgn3rldoq3jzj74iui53agq"
data = {"title": [], "user":[], "rating":[], "date":[], "review": [], 'spoil':[]}

while True:
    response = requests.get(url.format(key))
    soup = BeautifulSoup(response.content, "html.parser")
    # Find the pagination key
    pagination_key = soup.find("div", class_="load-more-data")
    if not pagination_key:
        break
    # Update the `key` variable in-order to scrape more reviews
    key = pagination_key["data-key"]
    for title, review, date, user, content in zip(
        soup.find_all(class_="title"), 
        soup.find_all(class_="text show-more__control"), 
        soup.find_all(class_="review-date"),
        soup.find_all(class_="display-name-link"), 
        soup.findAll(class_='lister-item-content')
    ):
        data["title"].append(title.get_text(strip=True))
        data["review"].append(review.get_text())
        data["date"].append(parse(date.get_text()).strftime("%Y-%m-%d"))
        data["user"].append(user.find('a')['href'].split('/')[-2])
        if content.find(class_='spoiler-warning')!=None:
            data["spoil"].append(True)
        else:
            data["spoil"].append(False)
        if content.find(class_='rating-other-user-rating')!=None:
            data["rating"].append(content.find(class_='rating-other-user-rating').get_text(strip=True).split('/')[0])
        else:
            data["rating"].append(None)
pd.DataFrame(data).to_csv('reviews_rat/'+movie+'.csv', index=False)

In [61]:
url = "https://www.imdb.com/title/tt6320628/reviews/_ajax?ref_=undefined&paginationKey={}"
key = "g4wp7bbfqqydoyyh7ovxrmbvrptm6cjhzfmxvlnomwklyczuf43o6ss7pe4vrprndr4k5xbfpgn3rldoq3jzj74iui53agq"
data = {"title": [], "user":[], "rating":[], "date":[], "review": [], 'spoil':[]}

while True:
    response = requests.get(url.format(key))
    soup = BeautifulSoup(response.content, "html.parser")
    # Find the pagination key
    pagination_key = soup.find("div", class_="load-more-data")
    if not pagination_key:
        break

    # Update the `key` variable in-order to scrape more reviews
    key = pagination_key["data-key"]
    for title, review, date, user, content in zip(
        soup.find_all(class_="title"), 
        soup.find_all(class_="text show-more__control"), 
        soup.find_all(class_="review-date"),
        soup.find_all(class_="display-name-link"), 
        soup.findAll(class_='lister-item-content')
    ):
        data["title"].append(title.get_text(strip=True))
        data["review"].append(review.get_text())
        
        data["date"].append(parse(date.get_text()).strftime("%Y-%m-%d"))
        data["user"].append(user.find('a')['href'].split('/')[-2])
        if content.find(class_='spoiler-warning')!=None:
            data["spoil"].append(True)
        else:
            data["spoil"].append(False)
        if content.find(class_='rating-other-user-rating')!=None:
            data["rating"].append(rating.get_text(strip=True).split('/')[0])
        else:
            data["rating"].append(None)
        
    break
# pd.DataFrame(data).to_csv('reviews_rat/'+movie+'.csv', index=False)

In [263]:
df.loc[438,'IMDBid'] = 'tt0063518'

In [269]:
df.loc[438, 'poster_url'] = 'https://imdb-api.com/posters/original/7ATiA88Vhq37h2LAjNyMR3fSpbf.jpg'
df.loc[438, 'trailer_url'] = 'https://www.imdb.com/video/vi2776891673'
df.loc[438, 'IMDB'] = '7.6'
df.loc[438, 'MetaCritic'] = '69'
df.loc[438, 'theMovieDb'] = '7.4'
df.loc[438, 'RottenTomatoes'] = ''
df.loc[438, 'FilmAffinity'] = '7.1'
df.loc[438, 'IMDB_male'] = '7.5'
df.loc[438, 'IMDB_female'] = '7.9'

In [273]:
df.loc[72, 'IMDBid'] = 'tt0272338'
df.loc[72, 'poster_url'] = ''
df.loc[72, 'trailer_url'] = 'https://www.imdb.com/video/vi3365732633'
df.loc[72, 'IMDB'] = '7.3'
df.loc[72, 'MetaCritic'] = '78'
df.loc[72, 'theMovieDb'] = '7.1'
df.loc[72, 'RottenTomatoes'] = ''
df.loc[72, 'FilmAffinity'] = '6.5'
df.loc[72, 'IMDB_male'] = '7.3'
df.loc[72, 'IMDB_female'] = '6.6'

In [275]:
url = "https://www.imdb.com/title/tt0272338/reviews/_ajax?ref_=undefined&paginationKey={}"
key = "g4wp7crlqm3t43yh7owhznburpumsbzhzfmxvlnomwklyczuf43o6ss2oa4vznridn4k5z7ep2m5x7ou34u6a3whyuwxbui"
data = {"title": [], "review": []}

while True:
    response = requests.get(url.format(key))
    soup = BeautifulSoup(response.content, "html.parser")
    # Find the pagination key
    pagination_key = soup.find("div", class_="load-more-data")
    if not pagination_key:
        break

    # Update the `key` variable in-order to scrape more reviews
    key = pagination_key["data-key"]
    for title, review in zip(
        soup.find_all(class_="title"), soup.find_all(class_="text show-more__control")
    ):
        data["title"].append(title.get_text(strip=True))
        data["review"].append(review.get_text())
pd.DataFrame(data).to_csv('reviews/tt0272338.csv', index=False)

In [277]:
df.to_csv('IMDB_with_api.csv', index=False)

#### Synopsis

In [300]:
driver = webdriver.Chrome('/Applications/chromedriver')

In [304]:
driver.get('https://www.imdb.com/title/tt0054997/plotsummary?ref_=tt_stry_pl#synopsis')

In [305]:
driver.find_elements_by_xpath('//*[@id="plot-synopsis-content"]')[0].text

'It looks like we don\'t have a Synopsis for this title yet.\nBe the first to contribute! Just click the "Edit page" button at the bottom of the page or learn more in the Synopsis submission guide.'

In [297]:
df[df['IMDBid'] == 'tt0119177']

,IMDBid,index,Title_en,URL,year,Problem,poster_url,trailer_url,IMDB,MetaCritic,theMovieDb,RottenTomatoes,FilmAffinity,IMDB_male,IMDB_female
296,tt0119177,m365,gattaca,https://www.imdb.com/title/tt0119177/?ref_=fn_...,1997,0.0,https://imdb-api.com/posters/original/eSKr5Fl1...,https://www.imdb.com/video/vi2611282201,7.8,64,7.6,83,7.3,7.8,7.8

In [301]:
no_synopsis = []
for movie in df['IMDBid'][296:]:
    try:
        driver.get(f'https://www.imdb.com/title/{movie}/plotsummary?ref_=tt_stry_pl#synopsis')
        synopsis = driver.find_elements_by_xpath('//*[@id="plot-synopsis-content"]')[0].text
        with open(f'synopsis/{movie}.txt', 'w') as f:
            f.write(synopsis)
        if 'It looks like we don\'t have a Synopsis for this title yet.' in synopsis:
            no_synopsis.append(movie)
    except:
        print(movie)

tt0099703
tt0054997

In [311]:
no_synopsis = []
for movie in df['IMDBid']:
    with open(f'synopsis/{movie}.txt', 'r') as f:
            if 'It looks like we don\'t have a Synopsis for this title yet.' in f.readline():
                no_synopsis.append(movie)
print(len(no_synopsis))

141

In [322]:
import os
for movie in no_synopsis:
    os.remove(f'synopsis/{movie}.txt')

Get storyline instead of synopsis:

In [313]:
driver.get(f'https://www.imdb.com/title/tt0099703/plotsummary?ref_=tt_stry_pl#summaries')
storylines = [summ.text for summ in driver.find_elements_by_xpath('//*[@id="plot-summaries-content"]')]

In [318]:
sorted(storylines, key=len)[0]

"A small-time conman has torn loyalties between his estranged mother and new girlfriend, both of whom are high-stakes grifters with their own angles to play.\nLily works for a bookie, placing bets to change the odds at the track. When her son is hospitalized after an unsuccessful con job and resultant beating, she finds that even an absentee parent has feelings for her child. This causes her own job to go wrong as well. Each of them faces the down side of the grift.\n—John Vogel <jlvogel@comcast.net>\nIn Los Angeles, the smalltime crook Roy Dillon is hit by a baseball bat in the stomach when he tries to swindle a bar attendant. His mother Lilly Dillon works in La Jolla for the powerful bookmaker Bobo Justus, who owns the Justus Amusement Company in Baltimore, placing bets to change the odds at the track but also stealing some money for her that she stashes in her Cadillac. When Lilly comes to Los Angeles to a horse race, she pays a visit to Roy after eight years without seeing each other, and she finds that he has an internal hemorrhage and sends him to the hospital, saving his life. When the experienced Lilly sees Roy's girlfriend, the slut and con artist Myra Langtry, she immediately finds that Myra is a roper. But the grieved Roy does not pay attention to his absent mother and decides to travel with Myra to La Jolla to spend a couple of days resting. Myra sooner finds that Roy lives of short-con grift and proposes him a great plan to rope tycoons; further she unravels Lilly's scheme with Bobo's money. When Roy turns Myra and her offer down, the greedy women set in motion a betrayal that brings tragic consequences to each player.\n—Claudio Carvalho, Rio de Janeiro, Brazil\nWhen con artist Roy Dillon (Cusack) is visited by his Mother, Lilly (Huston), who is also a con artist, she sends Roy off to the hospital because of a blow to the gut he suffered while working the grift. Roy's girlfriend, Myra (Bening), the third con artist, comes to visit Roy, and we discover that Lilly and Myra don't get along. After he is released from the hospital, Roy and Myra go on a little trip, where he is propositioned to be partners in crime with Myra. Everything soon falls apart for the three con artists, which leads to a bloody climax.\n—Justin Sharp <rainman88@earthlink.net>"

In [320]:
no_summaries = []
for movie in no_synopsis:
    try:
        driver.get(f'https://www.imdb.com/title/{movie}/plotsummary?ref_=tt_stry_pl#synopsis')
        storylines = [summ.text for summ in driver.find_elements_by_xpath('//*[@id="plot-summaries-content"]')]
        summary = sorted(storylines, key=len)[0]
        with open(f'summary/{movie}.txt', 'w') as f:
            f.write(summary)
        if 'It looks like we don\'t have' in summary:
            no_summaries.append(movie)
    except:
        print(movie)

In [323]:
print(no_summaries)

['tt0159519', 'tt9824546', 'tt0379907']

In [324]:
for movie in no_summaries:
    os.remove(f'summary/{movie}.txt')

#### Box Office

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('IMDB_with_api.csv')
df

,IMDBid,index,Title_en,URL,year,Problem,poster_url,trailer_url,IMDB,MetaCritic,theMovieDb,RottenTomatoes,FilmAffinity,IMDB_male,IMDB_female
0,tt0147800,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0.0,NaN,https://www.imdb.com/video/vi911933977,7.3,70.0,7.6,70.0,5.8,7.0,7.8
1,tt0103594,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0.0,https://imdb-api.com/posters/original/xVEynmeq...,https://www.imdb.com/video/vi1549188633,6.4,47.0,6.2,32.0,5.8,6.4,6.4
2,tt0118564,m10,affliction,https://www.imdb.com/title/tt0118564/?ref_=fn_...,1997,0.0,https://imdb-api.com/posters/original/hNu8ePwo...,https://www.imdb.com/video/vi727695641,6.9,79.0,6.4,88.0,7.1,6.9,6.7
3,tt0093260,m100,innerspace,https://www.imdb.com/title/tt0093260/?ref_=fn_...,1987,0.0,https://imdb-api.com/posters/original/A4azclZQ...,https://www.imdb.com/video/vi4136698137,6.8,66.0,6.8,82.0,6.3,6.8,6.9
4,tt0140352,m101,the insider,https://www.imdb.com/title/tt0140352/?ref_=fn_...,1999,0.0,https://imdb-api.com/posters/original/w695X0Fv...,https://www.imdb.com/video/vi1173618969,7.8,84.0,7.5,96.0,7.2,7.9,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,tt0480249,m95,i am legend,https://www.imdb.com/title/tt0480249/?ref_=fn_...,2007,0.0,https://imdb-api.com/posters/original/iPDkaSdK...,https://www.imdb.com/video/vi3820028185,7.2,65.0,7.2,68.0,6.5,7.2,7.2
613,tt0045917,m96,invaders from mars,https://www.imdb.com/title/tt0045917/?ref_=nv_...,1953,0.0,https://imdb-api.com/posters/original/pVR2c0bi...,https://www.imdb.com/video/vi3986670361,6.3,NaN,6.0,82.0,5.7,6.2,6.4
614,tt0116629,m97,independence day,https://www.imdb.com/title/tt0116629/?ref_=fn_...,1996,0.0,https://imdb-api.com/posters/original/p0BPQGSP...,https://www.imdb.com/video/vi2181957401,7.0,59.0,6.8,68.0,5.3,7.0,7.1
615,tt0097576,m98,indiana jones and the last crusade,https://www.imdb.com/title/tt0097576/?ref_=fn_...,1989,0.0,https://imdb-api.com/posters/original/sizg1AU8...,https://www.imdb.com/video/vi2007669529,8.2,65.0,7.8,88.0,7.8,8.3,8.1
616,tt0087469,m99,indiana jones and the temple of doom,https://www.imdb.com/title/tt0087469/?ref_=fn_...,1984,0.0,https://imdb-api.com/posters/original/wdv7Edut...,https://www.imdb.com/video/vi2444476697,7.5,57.0,7.3,84.0,7.4,7.5,7.5

In [17]:
driver.get(f'https://www.imdb.com/title/tt0147800/')

In [24]:
driver.find_element_by_css_selector('[data-testid="title-boxoffice-budget"]').text.split('$')

['預算\nUS', '30,000,000(估算值)']

In [26]:
budget = driver.find_element_by_css_selector('[data-testid="title-boxoffice-budget"]').text.split('$')
budget = budget[1].split(',')
budget[-1] = budget[-1][:3]
budget = ''.join(budget)
budget

'30000000'

In [11]:
driver.find_element_by_css_selector('[data-testid="title-boxoffice-cumulativeworldwidegross"]').text

'全球總額\nUS$53,478,579'

In [27]:
worldGross = driver.find_element_by_css_selector('[data-testid="title-boxoffice-cumulativeworldwidegross"]').text.split('$')
worldGross = worldGross[1].split(',')
worldGross[-1] = worldGross[-1][:3]
worldGross = ''.join(worldGross)
worldGross

'53478579'

In [12]:
driver.find_element_by_css_selector('[data-testid="title-boxoffice-grossdomestic"]').text

'美國和加拿大總額\nUS$38,178,166'

In [28]:
uscaGross = driver.find_element_by_css_selector('[data-testid="title-boxoffice-grossdomestic"]').text.split('$')
uscaGross = uscaGross[1].split(',')
uscaGross[-1] = uscaGross[-1][:3]
uscaGross = ''.join(uscaGross)
uscaGross

'38178166'

In [13]:
driver.find_element_by_css_selector('[data-testid="title-boxoffice-openingweekenddomestic"]').text

'美國和加拿大首映週末\nUS$8,330,6811999年4月4日'

In [29]:
opening = driver.find_element_by_css_selector('[data-testid="title-boxoffice-openingweekenddomestic"]').text.split('$')
opening = opening[1].split(',')
opening[-1] = opening[-1][:3]
opening = ''.join(opening)
opening

'8330681'

In [33]:
no_budget = 0
no_uscaGross = 0
no_opening = 0
no_worldGross = 0
budgets = []
worldGrosss = []
uscaGrosss = []
openings = []
cnt = 0
for movie in df['IMDBid']:
    driver.get(f'https://www.imdb.com/title/{movie}')
    try:
        budget = driver.find_element_by_css_selector('[data-testid="title-boxoffice-budget"]').text.split('$')
        budget = budget[1].split(',')
        budget[-1] = budget[-1][:3]
        budget = ''.join(budget)
        budgets.append(budget)
    except:
        budgets.append('')
        no_budget += 1
    try:
        worldGross = driver.find_element_by_css_selector('[data-testid="title-boxoffice-cumulativeworldwidegross"]').text.split('$')
        worldGross = worldGross[1].split(',')
        worldGross[-1] = worldGross[-1][:3]
        worldGross = ''.join(worldGross)
        worldGrosss.append(worldGross)
    except:
        worldGrosss.append('')
        no_worldGross += 1
    try:
        uscaGross = driver.find_element_by_css_selector('[data-testid="title-boxoffice-grossdomestic"]').text.split('$')
        uscaGross = uscaGross[1].split(',')
        uscaGross[-1] = uscaGross[-1][:3]
        uscaGross = ''.join(uscaGross)
        uscaGrosss.append(uscaGross)
    except:
        uscaGrosss.append('')
        no_uscaGross += 1
    try:
        opening = driver.find_element_by_css_selector('[data-testid="title-boxoffice-openingweekenddomestic"]').text.split('$')
        opening = opening[1].split(',')
        opening[-1] = opening[-1][:3]
        opening = ''.join(opening)
        openings.append(opening)
    except:
        openings.append('')
        no_worldGross += 1
    print(cnt, end=' ')
    cnt += 1

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616

In [34]:
print(no_budget,no_uscaGross,no_opening,no_worldGross)

84 106 0 228

In [35]:
for op in openings:
    if op == '':
        no_opening += 1
print(no_opening)

139

In [36]:
df['budget'] = budgets
df['openWeek'] = openings
df['WorldGross'] = worldGrosss
df['USCAGross'] = uscaGrosss
df

,IMDBid,index,Title_en,URL,year,Problem,poster_url,trailer_url,IMDB,MetaCritic,theMovieDb,RottenTomatoes,FilmAffinity,IMDB_male,IMDB_female,budget,openWeek,WorldGross,USCAGross
0,tt0147800,m0,10 things i hate about you,https://www.imdb.com/title/tt0147800/?ref_=fn_...,1999,0.0,NaN,https://www.imdb.com/video/vi911933977,7.3,70.0,7.6,70.0,5.8,7.0,7.8,30000000,8330681,53478579,38178166
1,tt0103594,m1,1492: conquest of paradise,https://www.imdb.com/title/tt0103594/?ref_=fn_...,1992,0.0,https://imdb-api.com/posters/original/xVEynmeq...,https://www.imdb.com/video/vi1549188633,6.4,47.0,6.2,32.0,5.8,6.4,6.4,47000000,3002680,7191399,7191399
2,tt0118564,m10,affliction,https://www.imdb.com/title/tt0118564/?ref_=fn_...,1997,0.0,https://imdb-api.com/posters/original/hNu8ePwo...,https://www.imdb.com/video/vi727695641,6.9,79.0,6.4,88.0,7.1,6.9,6.7,6000000,63979,6330054,6330054
3,tt0093260,m100,innerspace,https://www.imdb.com/title/tt0093260/?ref_=fn_...,1987,0.0,https://imdb-api.com/posters/original/A4azclZQ...,https://www.imdb.com/video/vi4136698137,6.8,66.0,6.8,82.0,6.3,6.8,6.9,27000000,4739913,25893810,25893810
4,tt0140352,m101,the insider,https://www.imdb.com/title/tt0140352/?ref_=fn_...,1999,0.0,https://imdb-api.com/posters/original/w695X0Fv...,https://www.imdb.com/video/vi1173618969,7.8,84.0,7.5,96.0,7.2,7.9,7.7,90000000,6712361,60289912,29089912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,tt0480249,m95,i am legend,https://www.imdb.com/title/tt0480249/?ref_=fn_...,2007,0.0,https://imdb-api.com/posters/original/iPDkaSdK...,https://www.imdb.com/video/vi3820028185,7.2,65.0,7.2,68.0,6.5,7.2,7.2,150000000,77211321,585410052,256393010
613,tt0045917,m96,invaders from mars,https://www.imdb.com/title/tt0045917/?ref_=nv_...,1953,0.0,https://imdb-api.com/posters/original/pVR2c0bi...,https://www.imdb.com/video/vi3986670361,6.3,NaN,6.0,82.0,5.7,6.2,6.4,290000,,,
614,tt0116629,m97,independence day,https://www.imdb.com/title/tt0116629/?ref_=fn_...,1996,0.0,https://imdb-api.com/posters/original/p0BPQGSP...,https://www.imdb.com/video/vi2181957401,7.0,59.0,6.8,68.0,5.3,7.0,7.1,75000000,50228264,817400891,306169268
615,tt0097576,m98,indiana jones and the last crusade,https://www.imdb.com/title/tt0097576/?ref_=fn_...,1989,0.0,https://imdb-api.com/posters/original/sizg1AU8...,https://www.imdb.com/video/vi2007669529,8.2,65.0,7.8,88.0,7.8,8.3,8.1,48000000,29355021,474171806,197171806
616,tt0087469,m99,indiana jones and the temple of doom,https://www.imdb.com/title/tt0087469/?ref_=fn_...,1984,0.0,https://imdb-api.com/posters/original/wdv7Edut...,https://www.imdb.com/video/vi2444476697,7.5,57.0,7.3,84.0,7.4,7.5,7.5,28000000,25337110,333107271,179870271

In [43]:
df.iloc[438, 3] = df.iloc[438, 3][7:].split('?ref_=')[0]

In [44]:
df.to_csv('IMDB_infos.csv', index=False)